language: node_js
node_js:
  - 10
sudo: false
install:
  - npm install -g coveralls
  - npm install
script:
  - npm run coverage-report
  - npm run docs:build
  - rm -r docs
  - mkdir docs
  - cp  docsource/playground/index.html docs/playground.html
  - cp  docsource/playground/app.js docs/app.js
  - cp -r docsource/docs/.vuepress/dist docs
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master
